### ISSUE TITLE
Signal K - MQTT Gateway: Failed to start: Expected `schema` to be an object or boolean

### ISSUE THREAD

**Issue by KEGustafsson** [tkurki/signalk-mqtt-gw#21] opened 2020-11-28 11:24 UTC
After update to v1.3.3 I get following errors in the Server Log.
Run local server needed to be selected.
Tried already to uninstall and reinstall it.
Node v12.

`Nov 28 11:17:42 error starting plugin: SchemaError: Expected `schema` to be an object or boolean
Nov 28 11:17:42 SchemaError: Expected `schema` to be an object or boolean at Validator.validate (/home/node/.signalk/node_modules/jsonschema/lib/validator.js:110:11) at Object.validate (/home/node/.signalk/node_modules/mosca/lib/options.js:264:26) at new Server (/home/node/.signalk/node_modules/mosca/lib/server.js:104:34) at startLocalServer (/home/node/.signalk/node_modules/signalk-mqtt-gw/index.js:162:14) at Object.plugin.start (/home/node/.signalk/node_modules/signalk-mqtt-gw/index.js:105:7) at doPluginStart (/home/node/signalk/lib/interfaces/plugins.js:252:20) at doRegisterPlugin (/home/node/signalk/lib/interfaces/plugins.js:359:13) at registerPlugin (/home/node/signalk/lib/interfaces/plugins.js:211:13) at /home/node/signalk/lib/interfaces/plugins.js:162:13 at Array.forEach (<anonymous>) at startPlugins (/home/node/signalk/lib/interfaces/plugins.js:161:63) at Object.start (/home/node/signalk/lib/interfaces/plugins.js:53:13) at /home/node/signalk/lib/index.js:361:70 at /home/node/signalk/node_modules/lodash/lodash.js:4925:15 at Function.forIn (/home/node/signalk/node_modules/lodash/lodash.js:12976:11) at startInterfaces (/home/node/signalk/lib/index.js:351:7) at /home/node/signalk/lib/index.js:270:13 at /home/node/signalk/lib/index.js:301:17 at getCertificateOptions (/home/node/signalk/lib/security.js:118:9) at createServer (/home/node/signalk/lib/index.js:295:9) at /home/node/signalk/lib/index.js:260:9 at new Promise (<anonymous>) at Server.start (/home/node/signalk/lib/index.js:259:12) at Object.<anonymous> (/home/node/signalk/bin/signalk-server:26:8) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14)`

**Comment by tkurki** [comment] 2020-11-28 13:16
This is a duplicate of #18. There is a remedy, but the real fix is more work.

**Closed as completed by tkurki** 2020-11-28 13:16 UTC
